baseURL = "https://raulcorreia7.dev"
languageCode = "en"
defaultContentLanguage = "en"
theme = "risotto"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 20

[markup]
  [markup.highlight]
    anchorLineNos = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 4
    wrapperClass = "highlight"
