disabled = false
languageCode = "en"
languageName = "English"
weight = 1

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  description = "Ra√∫l Correia personal blog"
