baseURL: "https://raulcorreia.dev"
title: Raul Correia
theme: risotto
languageCode: en
defaultContentLanguage: en
pagination:
  pagerSize: 20

params:
  dateFormat: "January 2, 2006"
  rtl: false
  customCSS: []
  customSCSS: []
  customJS: []
  mermaid: true

outputs:
  home:
    - HTML
    - RSS
