baseURL: "https://raulcorreia.dev/"
title: raulcorreia.dev
languageCode: en

params:
  description: "Raúl Correia's personal blog"
  dateFormat: "Jan 2, 2006"
  defaultAppearance: "dark"

  author:
    name: "Raúl Correia"

  social:
    github: "https://github.com/raulcorreia7/"
    linkedin: "https://www.linkedin.com/in/raul-correia/"

menu:
  main:
    - name: Posts
      pageRef: posts
      weight: 10
    - name: Categories
      pageRef: categories
      weight: 20
    - name: Tags
      pageRef: tags
      weight: 30
    - name: About
      identifier: about
      pageRef: about
      weight: 40

outputs:
  home: [HTML, RSS, JSON]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: true
    style: tokyonight-night
